export const LIKESTATUS = {
    LIKE: 'LIKE',
    DISLIKE: 'DISLIKE',
};

export const FRIENDSHIPSTATUS ={
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    BLOCKED: 'BLOCKED',
}

export const GLOBALSEARCHTYPE = {
    ALL: 'all',
    USERS: 'users',
    POSTS: 'posts',
};

export const POSTVISIBILITYSTATUS = {
    PUBLIC: "PUBLIC",
    PRIVATE: "PRIVATE",
    FRIENDS: "FRIENDS",
    FOLLOWERS: "FOLLOWERS",
    CUSTOM: "CUSTOM"
};

export const POSTVISIBLITYSTATUS = POSTVISIBILITYSTATUS;