export const QUERY_KEYS = {
  feed: ["feedPosts"],
  saved: ["savedPosts"],
  rooms: ["rooms"],
  friendRequests: ["friendRequests"],
  user: (id) => ["userDetail", id],
  userProfile: ["userProfile"],
  userPosts: ["userPosts"],
  post: (id) => ["post", id],
  globalSearch: (query, tab) => ["globalSearch", query, tab],
  instantSearch: (query) => ["instantSearch", query],
  privacySettings: ["privacySettings"],
  blockedUsers: ["blockedUsers"],
  privacyLists: ["privacyLists"],
  notifications: ["notifications"],
  stories: ["stories"],
  followers: ["followers"],
  following: ["following"],
  messages: (roomId) => ["messages", roomId],
};
