export const ROUTES = {
  HOME: '/',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  PROFILE: '/profile',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  UPDATE_PROFILE: '/update-profile',
  CHAT: '/chat',
  CHAT_ROOM: (roomId) => `/chat/${roomId}`,
  FRIENDS_DETAIL: (userId) => `/friends/${userId}`,
  SEARCH: '/search',
  USER_PROFILE: (userId) => `/user/${userId}`,
  FRIEND_REQUESTS: '/friend-requests',
  GROUPS: '/groups',
  GROUP_DETAIL: (groupId) => `/groups/${groupId}`,
  WATCH: '/watch',
  MARKETPLACE: '/marketplace',
  EVENTS: '/events',
  EVENT_DETAIL: (eventId) => `/events/${eventId}`,
  SAVED: '/saved',
  SHARE: '/share',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  POST_DETAIL: (postId) => `/posts/${postId}`,
  VIDEO_CALL: (roomId) => `/video-call/${roomId}`,

  // Informational pages
  ABOUT: '/about',
  FEATURES: '/features',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  HELP: '/help',
  GUIDELINES: '/guidelines',
  SAFETY: '/safety',
  BLOG: '/blog',
  NOT_FOUND: '*',
};
